### PR TITLE
fix url

### PR DESCRIPTION
**Pull request by RubenKelevra**
https://github.com/taigaio/taiga-front/issues/251

### CODE REVIEW

**Comment by bameda** [comment]
This change is not necessary

**Comment by RubenKelevra** [comment]
I set it up on a fresh ubuntu server and without this change the media-files did not work.

**Comment by bameda** [comment]
We install it a lot of times and we have no problems about that.

/static is the same as http://localhost:8000/static/ and MEDIA_URL will be http://localhost:8000/media/ instead http://localhost/media in this case.

However thank you very much for your contribution.

**Comment by RubenKelevra** [comment]
Well I changed the settings to default, and got:

"http://localhost:8000/media/attachments/7/a/9/1/505810719ad22bc879b3b536f401bb307d4a70ce7a5067e2854512f2e424/10feed407990-br-wan-day.png"

I think I forgot to change a definition elsewhere ... I had the following before in the config file, on live-setup:

MEDIA_URL = "http://taigaio.freifunk-nrw.de/media/"
STATIC_URL = "http://taigaio.freifunk-nrw.de/static/"
ADMIN_MEDIA_PREFIX = "http://taigaio.freifunk-nrw.de/static/admin/"

**Pull request closed without merging**
